#! /bin/bash
echo "== put-object"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix"
    exit 1
fi

OBJECT_KEY=$(basename "$2")

aws s3api put-object \
--bucket $1 \
--body $2 \
--key $OBJECT_KEY
