#! /bin/bash
echo "== sync"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix"
    exit 1
fi

# Location of the random temporary files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Remove the folder if it already exists
rm -r $OUTPUT_DIR

# Create the output folder
mkdir -p $OUTPUT_DIR

for((i=1; i<= 5; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/$2_$i.txt"

    # Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

ls $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$1/files